### ISSUE TITLE
Support for COPY COBOL conditional inclusion

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/dbb#106]
Hi,

We plan to implement IBM DBB to replace our current Application Lifecycle Management Source Control product for the construction and packaging parts.

We use IBM Enterprise COBOL V6, and we have taken advantage of conditional compilation to develop a framework of "adaptives" COPYBOOKs:
* conditional compilation variables are valued in the source code of the COBOL program; some are through DEFINE compiler options
* these compilation variables condition the inclusion of COPYBOOKs
* the COPYBOOKs in turn reference other COPYBOOKs, always conditionally, and this on several levels of inclusion
* COPYBOOKS modify the values of conditional compilation variables, and for some delete conditional compilation variables, (variables local to a group of COPYBOOKs)

For a COPYBOOK referenced in the COBOL source program, potentially dozens of other COPYBOOKs are referenced indirectly, but because of conditional compilation in reality only a small number of them participate in the compilation.

This operating mode also exists with the Assembler macros of the HLASM compiler.

According to our information, IBM DBB does not support COBOL conditional compilation at this time.

In fact, all the COPYBOOKs of our framework would be considered by IBM DBB as necessary for the construction of a COBOL program, which is not exact, and any modification of one of these COPYBOOKs of the framework could be identified as an impact on the program COBOL and wrongly trigger a reconstruction, (and in fact we would rebuild all the programs of our platform).

So we want IBM DBB to be able to handle COBOL conditional compilation.

Otherwise, it would be necessary to be able to declare to IBM DBB to ignore certain COPYBOOKs in the analyzes because these COPYBOOKs of framework have especially a technical character which one could consider as "non-impacting", and in the event of a real impact then we would handle the case outside of IBM DBB.

At this time, this operation of conditional inclusion of COPYBOOKs is only implemented for the development framework, it is not used for "business" COPYBOOKs, but in the future it could be.

**Comment by dennis-behm** [comment]
@FALLAI-Denis , apologies for the delayed response. Would you mind to open an idea (the new word for enhancement request) on the IBM ideas platform for : http://ideas.ibm.com/ .

This repository here contains samples/snippets which make use of IBM DBB, but is not used to prioritise new product functionality.

When browsing through the conditional compilation, doesn't that mean, that you pass on a particular compile option to the compiler to set the value for including a given leg in your application program in your build process (you referred to it as construction). 

Conditional compilation per se can be used also with DBB. However, you are right with the dependencies. Obviously - and this is correct for the scanner, if detects all dependencies  not only to a subset given some (external) condition.

**Comment by FALLAI-Denis** [comment]
Hi @dennis-behm 

I open an idea: [COBOL - Support for COPYBOOKs conditional inclusion](https://ibm-z-software-portal.ideas.ibm.com/ideas/DBB-I-23)

I have attached an example of a COBOL source program with the resulting listing showing conditional inclusions of COPYBOOKs.

**Comment by FALLAI-Denis** [comment]
Tracking on Ideas.
