### ISSUE TITLE
Question - IBM DBB Toolkit and EBCDIC 1047 files

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/dbb#112]
Hi,

Not related to this repository, I have an issue concerning IBM DBB Toolkit installation on USS. 

All files tagged "1047" and "autoconvert=yes" are in fact encoded with IBM-1147, wich is the codepage declared in our 3270 emulator. 

Files tagged "859" seems ok. 

Probably a mistake during our process deployment but I do'nt find it.

I do'nt participate to deployment process which is in charge of our system teams. 

Do you have ideas about this problem ?

Thanks for your help.

**Comment by dennis-behm** [comment]
Hi @FALLAI-Denis .

I might get your question wrong.

In USS, files are typically processed as IBM-1047. It is the default codepage on USS, and when JAVA loads a file, it is most likely in IBM-1047. 
Therefore the DBB Toolkit install with it's scripts is also encoded in IBM-1047. This is required to function correctly. 

This is independently on the set codepage in your emulator. When you edit files use IDZ, VS Code for it. This is not unique to DBB, but more generally a USS topic. If you use a 3270 emulator, you might need to switch to IBM-1047 for editing the configuration files.

For the build scripts, the groovy files therefore are also encoded/tagged as IBM-1047, while others - which are not used by the scripts like the readme - might stay in ASCII.

```
                    drwxr-xr-x   2 BPXROOT  ZSECURE     8192 Mar  9 11:24 utilities
                    drwxr-xr-x   4 BPXROOT  ZSECURE     8192 Mar  9 11:24 test
                    drwxr-xr-x   5 BPXROOT  ZSECURE     8192 Nov  1  2021 samples
                    drwxr-xr-x   2 BPXROOT  ZSECURE     8192 Mar  9 11:24 languages
t IBM-1047    T=on  -rw-r--r--   1 BPXROOT  ZSECURE    26072 Mar  9 11:52 build.groovy
                    drwxr-xr-x   2 BPXROOT  ZSECURE     8192 Mar  9 11:24 build-conf
t ISO8859-1   T=on  -rw-r--r--   1 BPXROOT  ZSECURE    11951 Mar  9 11:24 REPORT.md
t ISO8859-1   T=on  -rw-r--r--   1 BPXROOT  ZSECURE     6662 Mar  9 11:24 README.md
t ISO8859-1   T=on  -rw-r--r--   1 BPXROOT  ZSECURE    11355 Nov  1  2021 LICENSE
t ISO8859-1   T=on  -rw-r--r--   1 BPXROOT  ZSECURE     1236 Nov  1  2021 INSTALL.md
t IBM-1047    T=on  -rw-r--r--   1 BPXROOT  ZSECURE     1553 Nov  1  2021 DCO1.1.txt
t ISO8859-1   T=on  -rw-r--r--   1 BPXROOT  ZSECURE     1144 Nov  1  2021 CONTRIBUTIONS.md
t ISO8859-1   T=on  -rw-r--r--   1 BPXROOT  ZSECURE   120892 Mar  9 11:24 BUILD.md
```

**Comment by FALLAI-Denis** [comment]
Hi @dennis-behm 

Here is what I have on my setup:

```
/SYS9/DBB/P001/conf: >ls -lT                                                               
total 192                                                                                          
t ISO8859-1   T=on  -rwxr-xr-x   1 BPXROOT  OMVSGRP     2355 Sep 25  2020 BGZDBBP.jcl              
t IBM-1047    T=on  -rwxr-xr-x   1 BPXROOT  OMVSGRP     2336 Sep 25  2020 DBBS.jcl                 
t ISO8859-1   T=on  -rwxr-xr-x   1 BPXROOT  OMVSGRP     1473 Sep 25  2020 dbb.java.security        
t IBM-1047    T=on  -rwxr-xr-x   1 BPXROOT  OMVSGRP      762 Sep 25  2020 dbbenv.sh                
t IBM-1047    T=on  -rwxr-xr-x   1 BPXROOT  OMVSGRP     2096 Sep 25  2020 gitenv.sh                
t IBM-1047    T=on  -rwxr-xr-x   1 BPXROOT  OMVSGRP     1193 Sep 25  2020 jobStatus                
t ISO8859-1   T=on  -rwxr-xr-x   1 BPXROOT  OMVSGRP     1680 Sep 25  2020 log4j2.properties        
t IBM-1047    T=on  -rwxr-xr-x   1 BPXROOT  OMVSGRP     1676 Sep 25  2020 personaldaemon.sh        
t IBM-1047    T=on  -rwxr-xr-x   1 BPXROOT  OMVSGRP      677 Sep 25  2020 process_definitions.xml  
t ISO8859-1   T=on  -rwxr-xr-x   1 BPXROOT  OMVSGRP     2570 Sep 25  2020 rse-dbb.env              
t IBM-1047    T=on  -rwxr-xr-x   1 BPXROOT  OMVSGRP      566 Sep 25  2020 runIspf.sh               
t IBM-1047    T=on  -rwxr-xr-x   1 BPXROOT  OMVSGRP      787 Sep 25  2020 startdaemon.sh        
```   

In fact, after analyzing the files in TSO/ISPF 3.17 and displaying the hexadecimal encoding, the files are indeed encoded in 1047 (x7B for the # character).
But when I open them in VS Code with Zowe Explorer, they are transcoded incorrectly...
Either Zowe Explorer does not use tagging... or it takes the encoding declared on the z/OSMF profile which is 1147 in my case and applies the wrong conversion...

So everything is in order, sorry for the inconvenience.

**Comment by FALLAI-Denis** [comment]
User error...

**Comment by FALLAI-Denis** [comment]
In fact Zowe CLI / Zowe Explorer error... 

See https://github.com/zowe/zowe-cli/issues/1431
