### ISSUE TITLE
ISPF Client - application will crash if result of git command exceeds 32765 characters

### ISSUE THREAD

**Issue by JHSpijker** [IBM/dbb#118]
As the title says, the application will crash if the git command exceeds 32765 characters
When using commands like `git log` or `git diff`  this will very likely happen

Is it possible to use a temporary file for these situations, and just show the temporay file in View mode?
If possible, you could use it to add new menu options for use off `git log` or `git diff`

**Comment by donnellt** [comment]
@JHSpijker 

Command output from git commands (stdout and stderr) is collected into a REXX stem variable.  This stem variable is then formatted into a single REXX string variable to display the output correctly in an ISPF Pop-Up dialogue. For this instance (error) the length of the data collected in the REXX string variable exceeded the ISPF Dialogue CLIST variable data length maximum (REXX – 16Meg vs. CLIST/ISPF – 32K) causing the ISPF exception.

To correct this issue, a temporary working data set will be allocated at start-up time. The formatted git command output will be written to this temporary data set. Logic has been added to view this working data set if the length of the REXX string variable data exceeds the CLIST maximum.

Delivery time of this fix is still TBD.  Will keep you posted.

As for the request to add new menu options for `git log` and `git diff`, this seems like a reasonable request.  However, this request will need to be reviewed by the IBM development team.  If this is still important to you, would you please open a separate issue on this item.

**Comment by dennis-behm** [comment]
Delivered
