### ISSUE TITLE
NPE: property(name : "dbb-buildResultUrl", label: buildResult.getLabel(), value : buildResult.getUrl())

### ISSUE THREAD

**Issue by mhardin18** [IBM/dbb#131]
With the latest revision of the dbb-ucd-packaging.groovy script, out of the box behavior with DBB 1.1.2 results in an NPE on the various give lines of code.

property(name : "dbb-buildResultUrl", label: buildResult.getLabel(), value : buildResult.getUrl())

I have not tried to debug the issue.  But commenting the lines out for my purposes worked.
It doesn't seem that those properties are used anywhere that I could see on a casual view.

**Comment by dennis-behm** [comment]
Hi @mhardin18 , the packaging script is looking for the build result url in the build report to store a link in the UCD component version. This has not changed with recent update. Have you run a DBB build leveraging a `repositoryClient` connection? Do you see this BuildResult record?

![image](https://user-images.githubusercontent.com/28918869/190072360-ec0f1a3d-5e08-4889-a14a-0d1ef366927b.png)

**Comment by mhardin18** [comment]
So here is the issue.
I was using a userBuild BuildReport.json.
Which in my case, did not have the dbb URL.
In the past this has not failed when using a user build report.
Doing a team build, which included the dbb URL, this is not an issue.

**Comment by dennis-behm** [comment]
@mhardin18. Thanks for reporting the issue. 
Please see PR #146 to fix this.
