### ISSUE TITLE
Typo in DBB Documentation

### ISSUE THREAD

**Issue by AKippins** [IBM/dbb#160]
Hi I'm unsure if this is the right place to share this but you guys have a documentation typo. I couldn't find where the doc was generated. 

I'm assuming that this line
`As part of BM Z and Cloud Modernization Stack`

Should be 
`As part of IBM Z and Cloud Modernization Stack`

https://ibm.github.io/mainframe-downloads/products/ibm-dependency-based-build.html
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/2333708/231286674-4177b0be-f999-4b18-b392-bff9b29a3818.png">

**Comment by dennis-behm** [comment]
Typo is fixed.
