### ISSUE TITLE
workaround for missing #!/usr/bin/env 

### ISSUE THREAD

**Issue by gpow81** [IBM/dbb#171]
Hello, I hope I've come to the right place to seek help.

I'm encountering an issue with dbb and groove scripts, and while I do have some workarounds, I'm unsure which one is preferable. I'm also curious about why this issue is happening and whether there's an official document I could present to my client.

The user responsible for running dbb builds has Bash set as their default shell (configured via OMVS PROGRAM setting). The build process involves executing DBB_HOME/bin/groovez, which begins with "#!/bin/sh" as the interpreter in its first line. That script, in turn, calls DBB_HOME/groovy/bin/groovy, which uses "#/usr/bin/env sh" as its shebang. This is where the problem arises. Unfortunately, my client's system lacks env in /usr/bin and only has it in /bin. Consequently, creating a soft link is not favored by my client, as they believe it should work with the default setup.

To resolve this, I've identified three potential solutions:

Create a soft link: /bin/env -> /usr/bin/env
Change the shebang in groovy/bin/groovy to: #!/bin/env sh
Change the shebang in the main groovyz script to: #!/bin/bash. Surprisingly, I found that this solution works, even though the "child" script still references /usr/bin/env. Typically, in Linux, this would cause a "wrong interpreter" error.
I would greatly appreciate your insights and recommendations regarding the best course of action. Additionally, if you are aware of any official documentation that addresses this issue, it would be helpful to have it for presentation to my client.

Thank you for your assistance.

**Comment by dennis-behm** [comment]
Hi @gpow81,

I searched through the Unix System Services Customisation Guide, but did not find where this is specified. But anyway, the soft-link approach is the most favourable one.

There is enough evidence in other products running on Unix System Services, which require the soft-link as well to function. Our system also runs Python, and in the configuration states that the soft link needs to be configured:
https://www.ibm.com/docs/en/python-zos/3.8?topic=configuration-installing-configuring-smpe-edition

Using `#/usr/bin/env sh" as the shebang has the highest portability, and while the groovy that is shipped with DBB just ships what the official groovy implementation comes with.

Please open a defect or an IBM idea for DBB (https://ideas.ibm.com/new-idea) to funnel it to the product team. I think adding a similar step to the host customisation guide like Python makes sense.

**Comment by gpow81** [comment]
Thank you very much for your reply. I really appreciate the fast response and the link to Python's documentation. It's very helpful. I will follow up with IBM on this so they can update documentation.

**Comment by gpow81** [comment]
Yes, I did open an idea last week for this like you suggested. And yes, we can close this issue. Thank you very much Dennis for your help!

**Comment by dennis-behm** [comment]
@gpow81 Thank you for opening it. I noticed, that this is visible to IBM only - I don't see any confidential data in it. If you don't mind, can you make it visible to everyone please

**Comment by gpow81** [comment]
@dennis-behm unfortunately I am not seeing an option to change the visibility. I think once it is created, this option is gone. But i didn't put any confidential data into it at all. Can you see anything at all? It is in here https://ideas.ibm.com/ideas/DBB-I-50

**Comment by dennis-behm** [comment]
I am able to see it with my IBM id, yes. I will let an administrator change the visibility. I assume they will reach out to you.
