### ISSUE TITLE
Question | ArtifactRepositoryHelpers.groovy | Java 11  |   java.net.http.HttpRequest.*  | unable to resolve the class

### ISSUE THREAD

**Issue by APSDevp** [IBM/dbb#172]
Hi.

While trying to package and push the Artifacts to Jforg Artifactory - I am getting an error message as **java.net.http.HttpRequest.BodyPublishers** - unable to resolve the class - our shop has Java 11 installed and tried to add the classpath to the pipeline script as -cp/user/lpp.../java11.0_64/bin but still getting the error as script couldn't able to resolve the Jar file dependency

Where to find the required Jars in the Java 11 installed path? I couldn't find java.net.http.HttpRequest.* in the Java 11 path?

Help me resolve this

**Comment by dennis-behm** [comment]
This is not a matter of the Classpath, you need to set the correct `JAVA_HOME` environment variable before invoking `groovyz`.

**Comment by APSDevp** [comment]
Hi @dennis-behm 

Thanks, in our shop Java 8 is default in Java_Home. So In this case how to handle it? In Jenkins Agent shall I handle it?

**Comment by APSDevp** [comment]
Hi @dennis-behm 

Have resolved the class issue by adding the environment values in the pipeline however now getting the some security issues like PRIX..I need to connect internally on it? Expecting some certificate

**Comment by dennis-behm** [comment]
I assume you are running with HTTPS. This sounds like your local JAVA version in Unix System Services is missing your enterprise root certificates (CA cert). You need to work with your JAVA security team to get this fixed. Is this the first time with an outbound https communication from USS?

**Comment by dennis-behm** [comment]
Closing this one, please open a **discussion** for any follow-ups
