### ISSUE TITLE
Question | Calling a Db2 batch program using the MVSExec API

### ISSUE THREAD

**Issue by FALLAI-Denis** [IBM/dbb#176]
Hi,

Is it possible to execute a Db2 batch program, in particular a COBOL program, using the MVSExec API?

Should the program be prepared in a particular way (mode of attachment of the plan/package)? Does the bind package/plan need to be done in a particular way?

Are there any implementation examples? either at the IBM DBB level or at the JZOS level?

Thanks.

**Comment by dennis-behm** [comment]
@FALLAI-Denis ,

Like you would do in the JCL world as :

```
//jobname JOB USER=MY DB2ID
//GO EXEC PGM=IKJEFT01,DYNAMNBR=20
//STEPLIB DD DSN=prefix.SDSNEXIT,DISP=SHR
//        DD DSN=prefix.SDSNLOAD,DISP=SHR
⋮
//SYSTSPRT DD SYSOUT=A
//SYSTSIN DD *
DSN SYSTEM (ssid)
RUN PROG (SAMPPGM) -
  PLAN (SAMPLAN) -
  LIB (SAMPPROJ.SAMPLIB) -
  PARMS ('/D01 D02 D03')
END
/*
```

`IKJEFT01` cannot be invoked from MVSExec. (Let me cross check with the DBB team)
