### ISSUE TITLE
Issue / RFE for the DBB migration tool

### ISSUE THREAD

**Issue by dajsen** [IBM/dbb#19]
Info about migrating datasets to git: https://www.ibm.com/support/knowledgecenter/en/SS6T76_1.0.7/migration.html

On that page it says:
'After the local Git repository has been created on zFS, you can start using the the migration tool to copy source files from data set libraries to the local repository. 
In addition to copying the source from PDS to zFS, the migration tool also creates and updates the .gitattributes file. The .gitattributes file is required by Rocket's Git client to perform automatic codepage conversion between the Git server and the local Git repository during the migration.'

The migration tool might work ok when you are using the codepage IBM-1047 but when you are using something else it doesn't work so well.

What I would like is that the step where the DBB migration tool creates/updates the .gitattributes file is a choice (new parameter) for the user, If I want it created/updated or not.

What happens today?
We are using codepage IBM-278 (Swedish). My mappings file is correct. My .gitattributes file is correct.
After migration the code is correct, but the .gitattributes file is corrupt. Migration tool has added rows to the .gitattributes file with the standard codepage of IBM-1047.

Filing an issue/RFE on request by D. Behm

Thanks!

/N

**Comment by drbruce-git** [comment]
What version of the DBB toolkit are you using?  This issue was fixed in DBB v1.0.5 released in June 2019.

**Comment by dajsen** [comment]
OK, that's weird. We are using dbb 1.0.6 (will upgrade to dbb 1.0.7 asap). 
According to D. Behm same thing happens when using german codepage while running dbb 1.0.7.
