### ISSUE TITLE
Input fields for Repository Address and Working Directory are too small

### ISSUE THREAD

**Issue by JHSpijker** [IBM/dbb#25]
The input fields for the Repository Address and Working Directory are too small.
Mostly because we use on-premise git repo's

Repository Address is limited to only 44 characters
Working Directory is limited to only 19 characters

Due to the fact that for unknown reasons the panels are compiled (why would you do that)
I cant adjust the panels myself, which severely limits the use of the ISPF client.

Please provide alot more characters for Repository Address and Working Directory.

ps.
Request: provide panels just in plane text pls.

**Comment by xhouis** [comment]
On Git Repository panel, input fields for Repository Address and Working Directory are expendable fields (use PF4 to expend).
Each input fields have 1024 characters max.
Use PF3 after entering your value for these fields.

Concerning compiled panels (SBGZPENU data set), the corresponding dtl source panels are available in SBGZGML (containing panels entity description), and SBGZGMLI (containing panels body file imbed).
If you need to adjust the panels, update these dtl members, and use ISPF conversion utility ISPDTLC to convert the dtl sources to executable panels in SBGZPENU.
