### ISSUE TITLE
Automated cleanup of feature branches' collections

### ISSUE THREAD

**Issue by M-DLB** [IBM/dbb#254]
When a feature branch (or other "short-living" branches) are merged into `main`, the collections for these short-living branches are still present in the DBB metadatastore.
Over time, the DBB metadatastore will grow increasingly, which could lead to problems in managing the database's storage space.
Having a process provided by the CBS could help maintaining the size of the metadatastore, by removing the unnecessary collections for merged branches.

**Comment by nixpix49** [comment]
You had the functionality in pre DBB 2.0, but removed it. How come that you have changed your mind ?

**Comment by dennis-behm** [comment]
> You had the functionality in pre DBB 2.0, but removed it. How come that you have changed your mind ?

This is a bit more than the WebCleanUp Util that we had in the past, @nixpix49 :-) 

We believe a common house-keeping functionality that compares the list of active branches for a repository and the existing collections and build result groups would help a lot of customers to keep the DBB Metadatastore inventory clean. 

What do you think? Should the cleanup be fully automated, or is a list of "stale" collections/build result groups without a corresponding branch sufficient and we just generate the drop statements?

**Comment by nixpix49** [comment]
I love the fully automated approach, that would fit perfectly in our pipeline. But maybe that's just me, others may like the other solution, the drop statements so they can run those as they see fit. A CHOICE is always best, right @dennis-behm ;) ?

**Comment by dennis-behm** [comment]
Delivered as a common backend script via PR #255
