### ISSUE TITLE
Error when initializing a repo

### ISSUE THREAD

**Issue by mbabcock57** [IBM/dbb#30]
I'm getting this error when initializing a new repo.

record not written, error codes 71 571011C  
record not written, error codes 71 571011C  
record not written, error codes 71 571011C  
record not written, error codes 71 571011C  
record not written, error codes 71 571011C  
***                                         
TSO BPXMTEXT shows this for the 571011C error

571011C
BPXFSRDW 08/23/18                                                       
JRFileNotOpen: The file is not opened                                   
                                                                        
Action: Reissue the request specifying an open file descriptor.         
***                                                                     
                                   
The repo is init'd, the .git dir has files and directories and the .gitattributes is empty.  

I get this on both LPARs I have DBB 1.0.7 installed.

Am I doing something wrong or is there a bug?

**Comment by mbabcock57** [comment]
I traced the BGZINIT file and the file descriptor being returned in this call:

"open /u/xx35/test7/.gitattributes 147 755"      
 fd = retval                     
   "0"                       
Is returning fd 0 (zero, which is normally for STDIN)
    
The write call fails with a -1 (presumably because fd 0 is normally STDIN?)

"write 0 rec 15"      
if retval=-1                                                
  "-1"                                                      
  "1"                                                       
  "-1"                                                      
  "1"                                                       
 then                                                       
 say 'record not written, error codes' errno errnojr        
   "record not written, error codes"                        
   "71"                                                     
   "record not written, error codes 71"                     
   "571011C"                                                
   "record not written, error codes 71 571011C"

**Comment by dennis-behm** [comment]
Hi,
can you please share the entire output of your `git init` cmd?
Do you run this from the cmdline or any CI agent?
What version of git do you use on USS?
Probably it would be good to raise this question on the Rocket Git forum at: 
https://forum.rocketsoftware.com/c/rocket-z-os-open-source-languages-tools/13?order=activity

**Comment by mbabcock57** [comment]
Hi, I'm using the IBM ISPF Git Client provided by IBM in the DBB IDE directory.  Option 1.  This is a ISPF application with an interface to Rocket's Git port.  Output of git --version:

git version 2.14.4_zos_b09

This is a problem with the ISPF code, not the git client.  I've reported this to my IBM contact and they could reproduce the problem and have forwarded it to the developers.

**Comment by dennis-behm** [comment]
Thanks for sharing the details. We recently discussed a similar situation, if not yours.

**Comment by dennis-behm** [comment]
This issue has been resolved by the refresh of the ISPF client  through commit https://github.com/IBM/dbb/commit/2f154c21eb3f4b2d406c580852fdaeb4fb5261bb
