### ISSUE TITLE
Support new CopyToPDS build report records in CreateUCDComponentVersion Sample

### ISSUE THREAD

**Issue by drbruce-git** [IBM/dbb#42]
In DBB v1.0.8 the CopyToPDS build report record was extended so that it can contain the same information as the Execute records which would allow a copied JCL file from Git to a PDS to appear in the build report as a build step with output dataset and deploy type.  However it is not a DefaultRecordFactory.TYPE_EXECUTE record, but rather a DefaultRecordFactory.COPY_TO_PDS record.  In order for the new record to be collected by the CreateUCDComponentVersion sample a small change needs to be made to dbb-ucd-packaging.groovy.  When collecting the execute records, it also needs to collect CopyToPDS records:

```
// parse build report to find the build outputs to be deployed. 
println("** Find deployable outputs in the build report ")
// the following example finds all the build output with deployType set
def executes= buildReport.getRecords().findAll{
	(it.getType()==DefaultRecordFactory.TYPE_EXECUTE || it.getType()==DefaultRecordFactory.TYPE_COPY_TO_PDS)  && 
	!it.getOutputs().findAll{ o -> 
		o.deployType != null
	}.isEmpty()
} 
```

**Comment by dennis-behm** [comment]
Please see and review the opened PR #43 for supporting CopyToPDS build report records in the packaging script.

**Comment by dennis-behm** [comment]
Delivered
