### ISSUE TITLE
ERROR: Panel definition too large, greater than screen size

### ISSUE THREAD

**Issue by saketkhemka** [IBM/dbb#54]
We have cloned the GIT repository of the GIT ISPF client and moved that to USS server. We also ran the bgzgit.JCL to setup everything and it ran fine with return code of 0. We then modified the BGZCONF member to point to rocket GIT and other libraries.

When we ran the SBGZEXEC(BGZGIT), we got an error shown below -

ISPF Dialog Error
Command ===>

******************************************************************************
* ISPP121 *
* *
* Panel 'BGZMAIN' error *
* Panel definition too large, greater than screen size. *
* *
* *
* *
* *
* *
* *
* Panel line where error was detected: *
* Pé×ÙÉÔ@~@èÅâ@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ *
* *
* Enter HELP command for further information regarding this error. *
* Press ENTER key to terminate the dialog. *
* *
* *
* *
* *
******************************************************************************

**Comment by drbruce-git** [comment]
@xhouis  @campagboy  can you take a look at this when you get the chance?

**Comment by xhouis** [comment]
The ISPF panel body parameter for BGZMAIN is : )BODY WINDOW(76,24) 
So your screen dimensions of your IBM 3270 session (SCRSIZE operand), needs to be greater or equal than 24x80.

**Comment by saketkhemka** [comment]
Hi Xavier,

Thanks for the reply. I have the screen size as 43x80 and I still receive the error.

I tried setting the size to 24x80 but that didn’t help either.

[cid:image001.png@01D6989C.1CFB4E00]

Thanks,
Saket Khemka
Saket Khemka | Sr. Advisor, Mail Order Business Services, CVS/caremark
p 847-484-9370
CVS Health | 2100 Lake Cook Road, Buffalo Grove, IL, 60089
[CVS]
CONFIDENTIALITY NOTICE: This communication and any attachments may contain confidential and/or privileged information for the use of the designated recipients named above. If you are not the intended recipient, you are hereby notified that you have received this communication in error and that any review, disclosure, dissemination, distribution or copying of it or its contents is prohibited. If you have received this communication in error, please notify the sender immediately by email or telephone and destroy all copies of this communication and any attachments.

**Comment by campagboy** [comment]
@saketkhemka It looks to me, from the message, that the panel is in UTF-8 still and has not been converted to EBCDIC during the clone. In your USS directory where you cloned is there a .gitattributes file? If you use ISPF 3.17 and next to one of the files in the sbzupenu folder enter VU (View UTF8) this will confirm that. Did you clone on z/OS, or did you clone to windows/unix and then move the files to z/OS yourself. That is going to cause a problem as the panels are binary so cannot be converted. Let mw know, and we will work out what went wrong.

**Comment by saketkhemka** [comment]
That was the issue - I didn't clone directly in USS. I cloned in windows and moved the files to USS manually. Once I cloned directly in USS, it fixed the issue. Thanks a lot for your help.
