### ISSUE TITLE
CORS policy error trying to open build report during userbuild

### ISSUE THREAD

**Issue by nk2164** [IBM/dbb#55]
I run DBB user build and then, click on show build report when it completes , it just opens an empty browser with just a header "build report"

It looks like the report it is trying to open is from a local cached location in the workspace, so its ending up with a CORS policy error trying to open the BuildReport.json in the local folder. 

`Access to XMLHttpRequest at 'file:///C:/Users/xxxx/IBM/rationalsdp/workspace/RemoteSystemsTempFiles/xxxx/u/xxxx/DBB-Sandbox/work/BuildReport.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome-extension, edge, https, chrome-untrusted.`

Is there any way to resolve this ?

**Comment by dennis-behm** [comment]
There is currently no solution to fix it. Please stay tuned for the upcoming IDZ release.

**Comment by nk2164** [comment]
Thank you @dennis-behm . Will do. I will close the issue.
