### ISSUE TITLE
Pipeline: Adapt the UCD packaging script with UCD 7.1.x

### ISSUE THREAD

**Issue by jbyibm** [IBM/dbb#61]
With UCD 7.1.x for deploying binaries to Artifactory the -ar option is replaced with -prop options.

- https://www.ibm.com/support/knowledgecenter/SS4GSP_7.1.0/com.ibm.udeploy.doc/topics/zos_runtools_uss.html

The properties must have this format in the property file:

```
# Common external repository inputs             
EXTREPO.REPOSITORY_TYPE=Artifactory
EXTREPO.USERNAME=repo_user_id                            
EXTREPO.PASSWORD=repo_password                     
EXTREPO.URL=repo uri
EXTREPO.REPOSITORY=repo_path    
EXTREPO.APIKEY=XXXX
```

**Comment by jbyibm** [comment]
See PR: https://github.com/IBM/dbb/pull/62

**Comment by dennis-behm** [comment]
Merged
