### ISSUE TITLE
convert the json file lookup to a search 

### ISSUE THREAD

**Issue by nlopez59** [IBM/dbb#74]
DBB output dir is dynamically created with a timestamp making it hard to pass the absolute path of the buildreport.json file in a pipeline script 

Maybe we can replace 
def jsonOutputFile = new File("${properties.workDir}/BuildReport.json")

with 
def File jsonOutputFile = new FileNameFinder().getFileNames(properties.workDir, "**/BuildReport.json")

and change the readme to say the workDir is the path of the dbb workSpace

**Comment by drbruce-git** [comment]
zAppBuild does not create a time stamped subfolder for User Builds https://github.com/IBM/dbb-zappbuild/blob/development/build.groovy#L367 .  Seems an easy solution that would maintain backward compatibility is to add a new zAppBuild option or property to say don't create a time stamped subfolder.

**Comment by nlopez59** [comment]
I'll just add the one-line fix to the publish script to avoid compatibility issues.
