### ISSUE TITLE
dbb-ucd-packaging.groovy does not write artifacts to remote artifactory repository

### ISSUE THREAD

**Issue by sajordan** [IBM/dbb#77]
I am trying to write the output artifacts of the dbb-ucd-packaging.groovy to a remote artifactory repository NOT UCD CodeStation.  It is not updating the remote artifactory repository.

Property file:
![image](https://user-images.githubusercontent.com/42778244/116127682-20c4b680-a696-11eb-940d-af5e4d897004.png)

UCD Package Invocation:
![image](https://user-images.githubusercontent.com/42778244/116128236-b8c2a000-a696-11eb-9da6-dae506fd4d10.png)

UCD package Output:
![image](https://user-images.githubusercontent.com/42778244/116128387-e0b20380-a696-11eb-9b81-6af0e28ba9d0.png)

**Comment by dennis-behm** [comment]
The keys names for the external artefact repository have changed within the last couple of UCD versions, and are dependent on the UCD buztool version your are working with. Can you please verify that the properties are correct?

See the options for the buztool properties file at the end of the doc for V7.1.2  - they need to start with `EXTREPO.` 
https://www.ibm.com/docs/en/urbancode-deploy/7.1.2?topic=czcv-creating-zos-component-version-using-v2-package-format#zos_runtools_v2__section_orc_ldk_1mb

**Comment by dennis-behm** [comment]
@sajordan Is this issue resolved?

**Comment by sajordan** [comment]
Dennis,
 
Thank you , yes it is.
 
Steve JordanServices Specialist - DevOpsIBM Software Migration Project Office (SMPO) NAPhone: 1-919-543-7392Mail: ***@***.***
 
 
----- Original message -----From: Dennis Behm ***@***.***>To: IBM/dbb ***@***.***>Cc: sajordan ***@***.***>, Mention ***@***.***>Subject: [EXTERNAL] Re: [IBM/dbb] dbb-ucd-packaging.groovy does not write artifacts to remote artifactory repository (#77)Date: Wed, May 26, 2021 1:33 AM      @sajordan Is this issue resolved? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍    ZjQcmQRYFpfptBannerStart  

This Message Is From an External Sender
This message came from outside your organization. ZjQcmQRYFpfptBannerEnd 
 
@sajordan Is this issue resolved?
