### ISSUE TITLE
UCD packaging failed after code update

### ISSUE THREAD

**Issue by jbyibm** [IBM/dbb#92]
Now we have the COPY in the package with deploy type LOAD.

The code here need to be changed:
- https://github.com/IBM/dbb-zappbuild/blame/9b365a1be147ea4881697dd3b151c0789c0c1af9/languages/BMS.groovy#L78

replace L78 …
```
	compile.dd(new DDStatement().name("SYSPUNCH").dsn("${props.bms_cpyPDS}($member)").options('shr').output(true).deployType(deployType))
```
by
```
	compile.dd(new DDStatement().name("SYSPUNCH").dsn("${props.bms_cpyPDS}($member)").options('shr').output(true))
```

@dennis-behm  FYI

**Comment by dennis-behm** [comment]
Hi @jbyibm,

I am wondering if we should rather enhance the packaging script and add a parameter to exclude **deployTypes** from being added to the package.

We already have hard-coded it for the zunit-test-cases and we could externalise it to a property.

In that case your showcase would not be impacted by the recent addition in zAppBuild and provide a more generic approach to define what should be packaged and what not.

https://github.com/IBM/dbb/blob/2bb38b2be331a25ea309e713587e32051f9dd3b2/Pipeline/CreateUCDComponentVersion/dbb-ucd-packaging.groovy#L108

**Comment by jbyibm** [comment]
sounds good, but maybe a COPY should not have deployType LOAD ?

**Comment by dennis-behm** [comment]
There are situations where a COPY needs to be deployed, for instance to share with with other applications. I am closing this  one due to inactivity.
